openapi: 3.0.3
info:
  title: Contact API
  version: 1.0.0
paths:
  /v1/contacts:
    post:
      tags:
        - Contacts V1
      summary: Create a new contact
      operationId: createContact
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateContactRequest'
      responses:
        '201':
          description: Contact created successfully
components:
  schemas:
    CreateContactRequest:
      type: object
      properties:
        name:
          $ref: '#/components/schemas/Name'
        contactNumberList:
          type: array
          default: []
          items:
            $ref: '#/components/schemas/ContactNumber'
    Name:
      type: object
      properties:
        first:
          type: string
        last:
          type: string
        suffix:
          type: string
    ContactNumber:
      type: object
      properties:
        countryCode:
          type: string
        areaCode:
          type: string
        subscriberNumber:
          type: string